AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Secret Agent Data Redactor - S3 Object Access Point Demo

Resources:
  # S3 Bucket for classified reports
  ClassifiedReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda function for data redaction
  DataRedactorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 30
      Environment:
        Variables:
          DEFAULT_SECURITY_CLEARANCE: 'PUBLIC'
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: "*"
        - Statement:
          - Effect: Allow
            Action:
              - s3-object-lambda:WriteGetObjectResponse
            Resource: "*"

  # S3 Access Point
  ClassifiedReportsAccessPoint:
    Type: AWS::S3::AccessPoint
    Properties:
      Bucket: !Ref ClassifiedReportsBucket
      Name: classified-reports-ap

  # S3 Object Lambda Access Point
  RedactorObjectLambdaAccessPoint:
    Type: AWS::S3ObjectLambda::AccessPoint
    Properties:
      Name: secret-agent-redactor-olap
      ObjectLambdaConfiguration:
        SupportingAccessPoint: !GetAtt ClassifiedReportsAccessPoint.Arn
        TransformationConfigurations:
          - Actions:
              - GetObject
            ContentTransformation:
              AwsLambda:
                FunctionArn: !GetAtt DataRedactorFunction.Arn

  # Permission for S3 Object Lambda to invoke our function
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataRedactorFunction
      Action: lambda:InvokeFunction
      Principal: s3-object-lambda.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref ClassifiedReportsBucket
  
  AccessPointArn:
    Description: ARN of the S3 Access Point
    Value: !GetAtt ClassifiedReportsAccessPoint.Arn
  
  ObjectLambdaAccessPointArn:
    Description: ARN of the S3 Object Lambda Access Point
    Value: !GetAtt RedactorObjectLambdaAccessPoint.Arn
  
  TestCommand:
    Description: Command to test the redactor
    Value: !Sub |
      aws s3api get-object --bucket ${RedactorObjectLambdaAccessPoint} --key mission-report-001.json?clearance=CONFIDENTIAL --request-payer BucketOwner /tmp/redacted-report.json